---
title: "Collaborator Analysis"
format: html
editor: visual
author: "Miranda Tilcock"
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
library(DT)
lobster_traps <- read_csv("../data/Lobster_Trap_Counts_All_Years_20210519.csv")

glimpse(lobster_traps)
unique(lobster_traps$SITE)
head(lobster_traps)
```


```{r}

lobster_traps<- lobster_traps %>% 
  mutate(TRAPS = na_if(TRAPS,-99999))

unique(lobster_traps$TRAPS)


```

## Exercise: Data Visualization

```{r}

ggplot(data = lobster_traps, aes( x = TRAPS)) +
  geom_histogram() + 
  facet_wrap( ~YEAR)

```

```{r}

lobsters_traps_summarize <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarise(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))

ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS, color = SITE)) +
  geom_line(size = 0.7, alpha = 0.8) +
  geom_point(size = 1.7, alpha = 0.6) +
  theme_bw() +
  labs(x = "Year", 
       y = "Total number of traps",
       color = "Site",
       title = "Number of lobster traps colored by site seen each year") +
  theme(legend.position = "bottom") +
  scale_color_viridis_d()
  
ggsave("../figs/lobster_traps_by_year.jpg", width = 12, height = 6, units = "in")

```

## Making a table

```{r}

locations <- lobster_traps %>%
    distinct(SITE, .keep_all = T) %>%
    select(SITE, SEGMENT_START, SEGMENT_END)

head(locations)

datatable(locations)

```


